### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by timroster** [open-toolchain/simple-container-toolchain#28]
This first-time user container namespace link: https://console.bluemix.net/docs/containers/container_creating_ov.html#container_namespace lands on a "Sorry content not available" page.

**Comment by timroster** [comment]
perhaps it means to point at https://console.bluemix.net/docs/services/Registry/registry_setup_cli_namespace.html#registry_namespace_add

**Comment by hmagph** [comment]
This template is actually deprecated and will soon get removed. Please use instead https://github.com/open-toolchain/secure-kube-toolchain template.

**Comment by timroster** [comment]
tkx for pointer.
